name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # 当推送以v开头的标签时触发，例如v1.0.0
  workflow_dispatch: # 添加手动触发选项
    inputs:
      version-tag:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
      is-prerelease:
        description: 'Mark as pre-release'
        type: boolean
        default: false
      build-type:
        description: 'Build type'
        type: choice
        options:
          - apk
          - appbundle
        default: 'apk'

permissions:
  contents: write  # 允许写入内容（包括创建标签）

env:
  FLUTTER_VERSION: '3.32.0'
  BUILD_CACHE_KEY: ${{ github.sha }}
  ANDROID_BUILD_TOOLS: "34.0.0" # 与你的项目 build.gradle 保持一致

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录以便创建标签

      - name: Cache Flutter SDK and dependencies
        uses: actions/cache@v3
        id: flutter-cache
        with:
          path: |
            ~/flutter
            ~/.pub-cache
          key: flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('pubspec.lock') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ github.sha }}

      - name: Install dependencies
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          build-tools-version: ${{ env.ANDROID_BUILD_TOOLS }}
          platform-version: "34" # 对应 Android 14

      - name: Create version tag (manual trigger only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config --global user.name "laopaoer-wallet"
          git config --global user.email "laopaoer@protonmail.com"
          git tag ${{ github.event.inputs.version-tag }}
          git push origin ${{ github.event.inputs.version-tag }}

      - name: Build APK or App Bundle
        run: |
          if [ "${{ github.event.inputs.build-type || 'apk' }}" = "appbundle" ]; then
            flutter build appbundle --release
          else
            flutter build apk --release --split-per-abi
          fi

      - name: Sign APK (仅当构建类型为apk时执行)
        if: ${{ github.event.inputs.build-type == 'apk' || github.event.inputs.build-type == '' }}
        run: |
          # 1. 配置 Android SDK 路径
          export PATH="$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS }}:$PATH"
          
          # 2. 验证 apksigner 是否可用
          which apksigner
          apksigner --version

          # 3. 从GitHub Secrets获取签名密钥和密码
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/keystore.jks
          echo "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > keystore_password.txt
          echo "${{ secrets.KEY_PASSWORD }}" > key_password.txt

          # 4. 使用apksigner对APK进行签名
          for apk in build/app/outputs/flutter-apk/*.apk; do
            apksigner sign \
              --ks android/keystore.jks \
              --ks-pass file:keystore_password.txt \
              --key-pass file:key_password.txt \
              --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
              "$apk"
          done

          # 5. 验证签名
          for apk in build/app/outputs/flutter-apk/*.apk; do
            apksigner verify --verbose "$apk"
          done

          # 6. 清理敏感文件
          rm -f android/keystore.jks keystore_password.txt key_password.txt

      - name: Determine release info
        id: release-info
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.version-tag }}" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.event.inputs.version-tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "release_name=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-info.outputs.tag }}
          name: ${{ steps.release-info.outputs.release_name }}
          prerelease: ${{ github.event.inputs.is-prerelease || false }}
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}